site_name: FastJWT
site_description: FastAPI Plugin for reusable JWT Authentication Management
repo_name: ocarinow/fastjwt
repo_url: https://github.com/ocarinow/fastjwt
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.path
    - navigation.tracking
    - content.code.annotate
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            allow_inspection: true
            parameter_headings: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
nav:
  - Overview: index.md
  - Get Started:
      - get-started/install.md
      - get-started/base_usage.md
      - get-started/payload_data.md
  - JWT Locations: locations.md
  - Refreshing tokens: refresh.md
  - Token Freshness: fresh.md
  - Custom Callbacks:
      - callbacks/user.md
      - callbacks/token.md
  - Dependencies:
      - dependencies/injection.md
      - dependencies/deps.md
      - dependencies/aliases.md
      - dependencies/bundle.md
  - Claims: claims.md
  - Error Handling: errors.md
  - Configuration: config.md
  - Development:
      - Semantic Versioning: dev/semver.md
  - API:
      - api/types.md
      - api/fastjwt.md
      - api/config.md
      - api/deps.md
      - api/token_payload.md
      - api/request_token.md
      - api/exceptions.md

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ocarinow/fastjwt
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wbenbihi
    - icon: fontawesome/solid/globe
      link: https://ocarinow.com
