version: "3"

tasks:
  black:
    desc: "Run black hook on the project"
    cmds:
      - pre-commit run black --all-files
  flake8:
    desc: "Run flake8 hook on the project"
    cmds:
      - pre-commit run flake8 --all-files
  isort:
    desc: "Run isort hook on the project"
    cmds:
      - pre-commit run isort --all-files
  interrogate:
    desc: "Run interrogate hook on the project"
    cmds:
      - interrogate  --generate-badge ./docs/badges/interrogate.svg --badge-style flat
  # flake8:
  #   cmds:
  #     - poetry run flake8 fastjwt --statistics --tee --output-file ./reports/flake8stats.txt
