name: Documentation

on:
  workflow_run:
    workflows: [Publish]
    types:
      - completed

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
        name: Set up Poetry
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Deploy MkDoc
        run: |
          poetry install --no-interaction --no-root --with dev
          poetry run mkdocs gh-deploy --force
